<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "voices"
 *
 * Auto generated by Extension Builder 2015-05-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Voices',
	'description' => 'Konzertplan',
	'category' => 'plugin',
	'author' => 'Iris Schilke',
	'author_email' => 'ischilke@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);